#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

[ "$1" = "configure" ] || exit 0

# If there are what look like unmoved rcfiles, warn the administrator
if test -f /etc/zshenv || test -f /etc/zshrc || test -f /etc/zprofile || test -f /etc/zlogin; then
    db_input medium zsh/rcmove || true
    db_go
fi
