#!/bin/sh -e

# Move a conffile without triggering a dpkg question
mv_conffile() {
    OLDCONFFILE="$1"
    NEWCONFFILE="$2"

    if [ -e "$OLDCONFFILE" ]; then
        echo "Preserving user changes to $NEWCONFFILE ..."
        mv -f "$NEWCONFFILE" "$NEWCONFFILE".dpkg-new
        mv -f "$OLDCONFFILE" "$NEWCONFFILE"
    fi
}

case "$1" in
    (configure)
    if dpkg --compare-versions "$2" le "4.2.5-2"; then
        mv_conffile "/etc/zlogin" "/etc/zsh/zlogin"
        mv_conffile "/etc/zlogout" "/etc/zsh/zlogout"
        mv_conffile "/etc/zprofile" "/etc/zsh/zprofile"
        mv_conffile "/etc/zshenv" "/etc/zsh/zshenv"
        mv_conffile "/etc/zshrc" "/etc/zsh/zshrc"
    fi
	# continue below
    ;;

    (abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    (*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

if test -x /usr/bin/update-menus ; then update-menus ; fi

update-alternatives --remove zsh /usr/bin/zsh
update-alternatives --install /bin/zsh zsh /bin/zsh4 50 \
		--slave /usr/bin/zsh zsh-usrbin /bin/zsh4
update-alternatives --install /bin/rzsh rzsh /bin/zsh4 50 \
		--slave /usr/share/man/man1/rzsh.1.gz rzsh.1.gz /usr/share/man/man1/zsh.1.gz
update-alternatives --install /bin/ksh ksh /bin/zsh4 5 \
                    --slave /usr/bin/ksh usr.bin.ksh /bin/zsh4 \
                    --slave /usr/share/man/man1/ksh.1.gz ksh.1.gz /usr/share/man/man1/zsh.1.gz

mkdir -m2775 -p /usr/local/share/zsh/site-functions && chown root:staff \
               /usr/local/share/zsh/site-functions || true

add-shell /bin/zsh
add-shell /usr/bin/zsh

exit 0
